#include <Generic.h>
#include <p33EP128GP502.h>
#include <spi.h>
#include <pps.h>
#include "MicroIIFinalProjectHeader.h"

UINT16 SetupSPI(void)
{

    //SPI1STAT: SPIx status and control register
    SPI1STATbits.SPIEN = 0;         //disable the module
    SPI1STATbits.SPISIDL = 1;       //continue module in idle operation

    SPI1CON1bits.DISSCK = 0;        //Internal SPI clock is enabled
    SPI1CON1bits.DISSDO = 0;        //SDO pin is controlled by this module
    SPI1CON1bits.MODE16 = 1;        //communication is 8bit
    SPI1CON1bits.SMP = 0;           //input data sampled at middle of data output time
    SPI1CON1bits.CKE = 0;           //serial output data changes on transition from idle to active clock state
    SPI1CON1bits.SSEN = 0;          //slave select pin not used by module, pin controlled by port function
    SPI1CON1bits.CKP = 0;           // idle state low
    SPI1CON1bits.MSTEN = 1;         //activate master mode
    SPI1CON1bits.SPRE = 0b111;      //secondary prescaler
                                        //1:1
    SPI1CON1bits.PPRE = 0b11;       //primary prescale bits
                                        //1:1

    SPI1CON2bits.FRMEN = 0;         //framed spi support disabled
    SPI1CON2bits.SPIFSD = 0;        //not using frame mode
                                        //master
    SPI1CON2bits.FRMPOL = 1;        //not using frame mode
                                        //sync pulse is active high
    SPI1CON2bits.FRMDLY = 0;        //not using frame mode
                                        //frame sync precedes first bit clock


    SPI1STATbits.SPIEN = 1;         //enable the module
    
    //PPSOutput(OUT_FN_PPS_SCK2,OUT_PIN_PPS_RP42);
    //PPSOutput(OUT_FN_PPS_SDO2,OUT_PIN_PPS_RP43);


    /*
    OpenSPI1(ENABLE_SCK_PIN
            ,
            ENABLE_SDO_PIN &
            FRAME_ENABLE_OFF &          //not using frames
            FIFO_BUFFER_DISABLE &       //single word transmission - fifo not needed
            ENABLE_SDO_PIN &            //use the SPI_DATA_OUT pin for what I can only assume to be the Data out pin...
            SPI_MODE16_ON &             //Communication is 16 bit -> 8 bits of config and 8 bits of data
            SPI_SMP_OFF &               //sample input data in middle of data output time
            SPI_CKE_OFF &               //setting up with clock mode 1 found in the SPI family ref
                                        //transmit happens from idle state to active state
                                        //the Periph reads data on the rising edge of the SCLK
                                        //clock is ACTIVE HIGH (I hope this doesnt destroy everything)
            SLAVE_ENABLE_OFF &          //Dont use slave select
                                        //Page 14 of fam ref told me to in step 3.C
            CLK_POL_ACTIVE_HIGH &       //set clock to active high
            MASTER_ENABLE_ON &          //I AM THE MASTER NOW
            SEC_PRESCAL_8_1 &           //
            PRI_PRESCAL_64_1
            ,
            SPI_ENABLE &                //enable the module
            SPI_IDLE_CON                //continue in idle mode
            );

    ConfigIntSPI1(SPI_INT_DIS & SPI_INT_PRI_3);         //disable interrupts (assuming these are interrupts generated by SDI, which I am not using)

    */
    return 0;
}

